name: Bug report
description: Reportar un error
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Descripción
      description: ¿Qué pasó?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Pasos para reproducir
  - type: textarea
    attributes:
      label: Resultado esperado
